language: ruby
rvm:
- 2.1.1
env:
  SECRET_TOKEN="$(bundle exec rake secret)"
script:
- RAILS_ENV=test bundle exec rake db:drop db:create db:migrate db:seed
- bundle exec rake
before_script:
- psql -c 'create database lakara_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: XV+yJuaFXN66utYz+3hZdxzcwwU0EIroI24jDjhNnWyBQdy7RZNlWBd/cX4YSE1uXn2qGfzba7syFJMWAWH5bc+DyNMRrbX63T2tDPWRiEmfn383p0hBg1+UnnxrKv9gwz+lOWgiovOaJdLQ3Oqt5o9R4w3IJ1zHdsRW65U3sHY=
  app: lakara
  on:
    repo: sriki77/lakara
  run:
  - rake db:migrate
  - rake db:seed
  - restart
